const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "app.js"), "utf8");
const refreshScript = fs.readFileSync(path.join(root, "courseware-refresh.js"), "utf8");
const server = fs.readFileSync(path.join(root, "server.js"), "utf8");
const imageScript = fs.readFileSync(path.join(root, "scripts", "gemini-generate.ps1"), "utf8");
const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const refreshCss = fs.readFileSync(path.join(root, "courseware-refresh.css"), "utf8");
const vercelConfig = fs.readFileSync(path.join(root, "vercel.json"), "utf8");
const vercelGemini = fs.readFileSync(path.join(root, "lib", "gemini.js"), "utf8");
const vercelStatus = fs.readFileSync(path.join(root, "api", "status.js"), "utf8");
const vercelStory = fs.readFileSync(path.join(root, "api", "generate-story.js"), "utf8");
const vercelImage = fs.readFileSync(path.join(root, "api", "generate-image.js"), "utf8");
const conceptImageFiles = ["ai-listen.svg", "ai-draw.svg", "ai-mistake.svg"];
const slideCount = (html.match(/<section class="[^"]*\bslide\b/g) || []).length;
const tabCount = (html.match(/<button class="tab\b/g) || []).length;

const forbiddenStageCopy = [
  "支持语音输入",
  "老师手动输入",
  "建议每个孩子",
  "额外奖励",
  "现场网络不好",
  "备用演示"
];

for (const phrase of forbiddenStageCopy) {
  assert.equal(html.includes(phrase), false, `classroom-facing HTML should not contain: ${phrase}`);
}

assert.match(html, /id="generateImage"/, "image generation control should exist");
assert.match(html, /id="courseCover"/, "courseware should include a fullscreen pre-class cover");
assert.match(html, /id="coverStart"/, "course cover should enter the lesson on click");
assert.match(html, /class="cover-animal"/, "course cover should include an SVG cartoon animal mascot");
assert.equal(slideCount, 14, "courseware should contain 14 classroom slides after adding AI fraud awareness");
assert.equal(tabCount, 14, "courseware navigation should contain 14 step tabs");
assert.match(html, /<span id="stepTotal">14<\/span>/, "footer should show 14 total steps before hidden classroom-only slides are removed");
assert.match(html, /开场破冰/, "courseware should include the icebreaker page");
assert.match(html, /魔法变装/, "icebreaker page should include magic costume moment");
assert.match(html, /会说话、会思考的机器人/, "icebreaker page should include the robot question");
assert.match(html, /小爱同学/, "icebreaker page should include life examples for children");
assert.match(html, /AI是怎么学习的/, "courseware should include the AI learning page");
assert.match(html, /知识糖果/, "AI learning page should explain examples as knowledge candy");
assert.match(html, /data-learning-card="apple"/, "AI learning page should include apple guessing cards");
assert.match(html, /像苹果的西红柿/, "AI learning page should include the tomato counterexample");
assert.match(html, /我们都是小魔法师/, "courseware should include the final magician page");
assert.match(html, /AI AI，好好学习，天天向上/, "final magician page should include the group spell");
assert.match(html, /长颈鹿戴领带/, "final magician page should include the optional home challenge");
assert.match(html, /id="liliPrompt"/, "Xiao Lili creation input should exist");
assert.match(refreshScript, /栗子帽/, "Xiao Lili prompt should use the chestnut-hat base character");
assert.match(refreshScript, /红脸蛋/, "Xiao Lili prompt should include red cheeks");
assert.match(html, /data-jump="8">翻牌<\/button>/, "navigation should label the generated memory game as flip-card");
assert.match(html, /data-jump="10">防欺诈<\/button>/, "navigation should include AI fraud awareness");
assert.match(html, /id="fraudImage"/, "AI fraud slide should show a large image");
assert.match(html, /data-fraud-answer="ai"/, "AI fraud slide should include AI image answer button");
assert.match(html, /data-fraud-answer="real"/, "AI fraud slide should include real image answer button");
assert.match(html, /class="slide game-slide"/, "rainbow matching game should have its own slide");
assert.match(html, /data-game-scene="rainbow"/, "game should provide selectable scene cards");
assert.match(html, /data-game-scene="space"/, "game should provide a space scene option");
assert.match(html, /data-game-scene="ocean"/, "game should provide an ocean scene option");
assert.match(html, /id="buildGame"/, "game should include a button to build the mini game");
assert.match(html, /id="gameStage"/, "game should include an interactive game stage");
assert.match(html, /id="matchLines"/, "game should include SVG rainbow connection lines");
assert.match(html, /data-match-side="left"/, "game should include Chinese matching cards");
assert.match(html, /data-match-side="middle"/, "game should include English matching cards");
assert.match(html, /data-match-side="right"/, "game should include picture matching cards");
assert.match(html, /id="englishMatchCards"/, "game should separate English cards from picture cards");
assert.match(html, /id="pictureMatchCards"/, "game should separate picture cards from English cards");
assert.match(html, /id="gameFeedback"/, "game should include visible feedback");
assert.match(html, /小立立/, "courseware should include Xiao Lili activity");
assert.match(html, /class="cartoon-loader/, "courseware should include cartoon loading animation markup");
assert.match(html, /id="storyLoading"/, "story generation should show a cartoon loading animation");
assert.match(html, /id="imageLoading"/, "image generation should show a cartoon loading animation");
assert.match(html, /id="liliLoading"/, "Lili generation should show a cartoon loading animation");
assert.equal(html.includes("姐姐朗读"), false, "read buttons should be icon-only, not text labels");
assert.equal(html.includes("姐姐讲故事"), false, "story read button should be icon-only, not text labels");
assert.match(html, /class="play-button/, "read buttons should use cartoon play button class");
assert.match(html, /data-mascot="robot"/, "homepage robot mascot should be selectable");
assert.match(html, /data-mascot="bunny"/, "homepage bunny mascot should be selectable");
assert.match(html, /data-mascot="kitten"/, "homepage kitten mascot should be selectable");
assert.match(html, /id="floatingMascot"/, "selected mascot should appear as floating assistant");
assert.match(html, /id="magicBurst"/, "magic button should trigger a visible burst effect");
assert.match(html, /id="fullMagic"/, "magic button should trigger fullscreen floating icons");
assert.match(html, /data-concept="listen"/, "AI concept cards should be interactive");
assert.match(html, /id="conceptVisual"/, "AI concept cards should update a visual demo");
assert.match(html, /id="conceptImage"/, "AI concept visual should display a pre-generated image");
assert.match(html, /images\/ai-listen\.svg/, "AI concept visual should start with the listening image");
assert.match(html, /class="word-bank"/, "story page should provide selectable word chips");
assert.match(html, /data-word="小兔子"/, "word bank should include classroom-friendly word options");
assert.match(html, /class="prompt-compare"/, "prompt page should compare simple prompt and magic prompt results");
assert.match(html, /class="cartoon-icon/, "prompt labels should use cartoon icons instead of text-only icons");
assert.match(html, /class="error-demo/, "detective page should show concrete visual error examples");
assert.equal(html.includes("今日小奖项\n              <textarea"), false, "gift awards should not be inside a textarea");
assert.equal(html.includes('data-voice-target="namesInput"'), false, "gift page should not have microphone input");
assert.equal(html.includes('id="addStar"'), false, "gift page should not use star button");
assert.match(html, /detective-choice/, "detective activity should have interactive choices");
assert.match(html, /award-card/, "gift page should reveal awards as designed cards");
assert.match(html, /class="badge-gift"/, "final page should show a badge for every child");
assert.match(script, /\/api\/generate-image/, "frontend should call local image generation proxy");
assert.match(script, /\/api\/generate-story/, "frontend should call local Gemini text generation proxy");
assert.match(script, /setLoading\(/, "frontend should use shared loading state helper");
assert.match(script, /AudioContext|webkitAudioContext/, "frontend should create lightweight click sounds");
assert.match(script, /playUiSound/, "frontend should play UI interaction sounds");
assert.match(script, /pointerenter/, "frontend should react to hover with subtle sound");
assert.match(script, /selectMascot/, "frontend should support mascot selection");
assert.match(script, /announceMascotHover/, "frontend should say pick-me prompt on mascot hover");
assert.match(script, /showMagicBurst/, "frontend should show cute magic burst");
assert.match(script, /showFullMagic/, "frontend should show fullscreen floating magic icons");
assert.match(script, /setConceptVisual/, "frontend should update AI concept visual examples");
assert.match(script, /conceptImages/, "frontend should map concept cards to pre-generated images");
assert.match(script, /conceptImage\.src/, "frontend should switch the concept image on click");
assert.match(script, /toggleWordChip/, "frontend should support selectable story words");
assert.match(script, /checkDetectiveAnswer/, "frontend should support detective answer interaction");
assert.match(script, /gameScenes/, "frontend should define scene-driven game content");
assert.match(script, /toggleGameScene/, "frontend should support selecting game scenes");
assert.match(script, /buildRainbowGame/, "frontend should build the Xiaolili rainbow matching game");
assert.match(script, /handleMatchCard/, "frontend should handle matching-card clicks");
assert.match(script, /selectedMatchCards/, "frontend should require selecting Chinese, English, and picture cards together");
assert.match(script, /selectedSides\.every/, "frontend should validate all three sides before a match counts");
assert.match(script, /drawMatchLine/, "frontend should draw rainbow match feedback");
assert.match(script, /awardIndex/, "gift page should reveal awards one by one");
assert.match(css, /--tab-gradient/, "navigation should use per-step gradient variables");
assert.match(css, /tabBounce/, "navigation hover should include a playful bounce animation");
assert.match(css, /\.tab::after/, "navigation tabs should have animated sparkle layer");
assert.match(css, /clip-path: polygon/, "cards should use playful irregular shapes");
assert.match(css, /floating-mascot/, "selected helper should have floating mascot styles");
assert.match(css, /magic-burst/, "magic burst should have visible animation styles");
assert.match(css, /full-magic/, "fullscreen magic icons should have visible animation styles");
assert.match(css, /white-space: nowrap/, "slide titles should stay on one line");
assert.match(css, /slide-copy h2/, "slide titles should be positioned as full-width slide banners");
assert.match(css, /concept-image/, "AI concept pre-generated images should have display styles");
assert.match(css, /icebreaker-slide/, "icebreaker page should have dedicated visual styles");
assert.match(css, /learning-slide/, "AI learning page should have dedicated visual styles");
assert.match(css, /magician-slide/, "final magician page should have dedicated visual styles");
assert.match(css, /apple-gallery/, "AI learning page should style the apple guessing activity");
assert.match(css, /chant-spell/, "final magician page should style the group spell");
assert.match(css, /game-slide/, "rainbow matching game should have dedicated styles");
assert.match(css, /scene-picker/, "game scene picker should have styles");
assert.match(css, /matching-card/, "game matching cards should have styles");
assert.match(css, /english-column/, "game should style the English card column");
assert.match(css, /picture-column/, "game should style the picture card column");
assert.match(css, /match-lines/, "game rainbow connection lines should have styles");
assert.match(css, /word-bank/, "word bank should have cute selectable chip styles");
assert.match(css, /prompt-compare/, "prompt comparison should have visual styles");
assert.match(css, /error-demo/, "detective visual error examples should have styles");
assert.match(css, /firework/, "gift page should include firework effects");
assert.match(script, /location\.protocol === "file:"/, "frontend should detect direct file opening");
assert.match(script, /http:\/\/localhost:3000/, "direct file opening should call localhost API");
assert.match(server, /GEMINI_IMAGE_MODEL/, "image proxy should use Gemini image model constant");
assert.match(server, /gemini-3\.1-flash-image-preview/, "image proxy should call current Gemini image generation model");
assert.match(server, /responseModalities: \["TEXT", "IMAGE"\]/, "image proxy should request image output modalities");
assert.match(server, /GEMINI_TEXT_MODEL/, "text proxy should use Gemini text model constant");
assert.match(server, /gemini-2\.5-flash/, "text proxy should call Gemini text generation");
assert.match(server, /makeFallbackStory/, "story generation should have classroom-safe fallback");
assert.match(server, /words\.every\(\(word\) => story\.includes\(word\)\)/, "story generation should validate required words");
assert.equal(server.includes("gpt-image-2"), false, "server should no longer call OpenAI image models");
assert.equal(server.includes("api.openai.com"), false, "server should no longer call OpenAI endpoints");
assert.match(server, /request\.url === "\/api\/status"/, "server should expose non-secret status endpoint");
assert.match(server, /geminiApiKeyConfigured: Boolean\(getGeminiApiKey\(\)\)/, "status endpoint should report Gemini key presence without exposing it");
assert.match(vercelConfig, /api\/\*\.js/, "Vercel should deploy the serverless API functions");
assert.match(vercelGemini, /process\.env\.GEMINI_API_KEY/, "Vercel API should read Gemini API key from server environment");
assert.match(vercelStatus, /geminiApiKeyConfigured/, "Vercel status endpoint should report key configuration");
assert.match(vercelStory, /callGemini/, "Vercel story endpoint should call Gemini server-side");
assert.match(vercelImage, /extractImage/, "Vercel image endpoint should extract Gemini inline image data");
assert.equal(vercelGemini.includes("AIza"), false, "Vercel helper must not contain a hard-coded Gemini key");
assert.match(server, /loadLocalEnv/, "server should support loading a local env file for Gemini keys");
assert.match(server, /Access-Control-Allow-Origin/, "image proxy should allow browser requests from direct file opening");
assert.match(server, /request\.method === "OPTIONS"/, "image proxy should handle CORS preflight");
assert.match(server, /gemini-generate\.ps1/, "server should have PowerShell fallback for Windows system proxy");
assert.match(server, /\.gemini-request\.json/, "server should pass UTF-8 request file to PowerShell fallback");
assert.match(server, /parseJsonFromText/, "server should preserve upstream JSON errors from fallback");
assert.match(imageScript, /generativelanguage\.googleapis\.com/, "PowerShell fallback should call Gemini API");
assert.match(imageScript, /gemini-3\.1-flash-image-preview/, "PowerShell fallback should support current Gemini image model");
assert.match(imageScript, /responseModalities = @\("TEXT", "IMAGE"\)/, "PowerShell fallback should request image output modalities");
assert.match(imageScript, /gemini-2\.5-flash/, "PowerShell fallback should support Gemini text model");
assert.match(imageScript, /InputEncoding = \[System\.Text\.UTF8Encoding\]::new/, "PowerShell fallback should read UTF-8 prompts");
assert.match(imageScript, /Get-Content -LiteralPath \$InputPath -Raw -Encoding UTF8/, "PowerShell fallback should read request files as UTF-8");
assert.match(imageScript, /UTF8\.GetBytes\(\$body\)/, "PowerShell fallback should send UTF-8 JSON bytes");
assert.match(imageScript, /application\/json; charset=utf-8/, "PowerShell fallback should declare UTF-8 JSON");
assert.equal(imageScript.includes("sk-proj"), false, "PowerShell fallback must not contain secrets");
assert.equal(/data-voice-target="word[123]"/.test(html), false, "short story words should not use voice input");
assert.equal(/data-voice-target="(hero|color|place|action|mood)"/.test(html), false, "short prompt fields should not use voice input");

for (const fileName of conceptImageFiles) {
  const imagePath = path.join(root, "images", fileName);
  assert.equal(fs.existsSync(imagePath), true, `concept image should exist: images/${fileName}`);
  assert.match(fs.readFileSync(imagePath, "utf8"), /<svg/, `concept image should be an SVG: images/${fileName}`);
}

assert.match(html, /courseware-refresh\.css/, "courseware should load the refresh styles");
assert.match(html, /courseware-refresh\.js/, "courseware should load the refresh script");
assert.match(refreshScript, /cursorSprinkles/, "refresh script should add colorful cursor sprinkles");
assert.match(refreshScript, /setupCourseCover/, "refresh script should initialize the pre-class cover");
assert.match(refreshScript, /showCoverLaunch/, "course cover should show a fullscreen cartoon launch effect");
assert.match(refreshScript, /pointerenter/, "course cover start button should play a hover sound");
assert.equal(refreshScript.includes("基础形象是可爱的卡通小伙伴"), false, "Xiao Lili prompt should not include the old base-shape wording");
assert.match(refreshScript, /setLifeExample/, "refresh script should switch icebreaker example pictures");
assert.match(refreshScript, /life-xiaoai-real\.jpg/, "icebreaker should use a local XiaoAI image");
assert.match(refreshScript, /life-vacuum-real\.(png|jpg)/, "icebreaker should use a real local robot vacuum product image");
assert.match(refreshScript, /life-car-real\.jpg/, "icebreaker should use a real local smart car product image");
assert.match(refreshScript, /train-red-apple\.jpg/, "AI learning should use a real red apple photo");
assert.match(refreshScript, /train-green-apple\.jpg/, "AI learning should use a real green apple photo");
assert.match(refreshScript, /train-bitten-apple\.jpg/, "AI learning should use a real bitten apple photo");
assert.match(refreshScript, /train-tomato-real\.jpg/, "AI learning should use a real tomato photo");
assert.match(refreshScript, /speakFeedback/, "AI learning feedback should be spoken aloud");
assert.match(refreshScript, /setupPromptDuel/, "refresh script should rebuild the prompt page as a left-right image comparison");
assert.equal(refreshScript.includes("cat-placeholder"), false, "prompt comparison should not show default cartoon placeholders");
assert.match(refreshScript, /simpleCatBackendPrompt/, "simple cat image generation should use a hidden backend prompt");
assert.match(refreshScript, /画面里只能有一只小猫/, "simple cat backend prompt should strictly limit the image to one cat");
assert.match(refreshScript, /requestArtDetectiveImage/, "art detective should hide the intentional error in the backend prompt");
assert.match(refreshScript, /setupMazeGame/, "refresh script should replace matching cards with an AI-generated classroom game");
assert.match(refreshScript, /memoryAnimals/, "refresh script should define memory flip animals");
assert.equal(refreshScript.includes("H5记忆翻牌小游戏"), false, "memory game title should not include H5");
assert.match(refreshScript, /展示10秒钟/, "memory game prompt should show cards for 10 seconds");
assert.match(refreshScript, /countdown: 10/, "memory game countdown should be 10 seconds");
assert.match(refreshScript, /beginMemorySpell/, "memory game should have a one-click spell generation step");
assert.match(refreshScript, /previewMemoryGame/, "memory game should require running or previewing after generation");
assert.match(refreshScript, /startMemoryGame/, "memory game should show animals before hiding cards");
assert.match(refreshScript, /hideApplauseStep/, "refresh script should hide the applause page");
assert.match(refreshScript, /data-jump="13"|data-jump='13'/, "refresh script should hide the closing page from the classroom flow");
assert.match(refreshScript, /setupDetective/, "refresh script should rebuild the detective activity");
assert.match(refreshScript, /setupAiFraud/, "refresh script should initialize AI fraud awareness activity");
assert.match(refreshScript, /fraudImages/, "AI fraud activity should define the local image carousel");
assert.match(refreshScript, /answerFraud/, "AI fraud activity should validate AI versus real choices");
assert.match(refreshScript, /setupImageFullscreen/, "all classroom images should support fullscreen viewing");
assert.match(refreshScript, /imageFullscreenOverlay/, "fullscreen image viewer should use an overlay");
assert.match(refreshScript, /six-fingers-photo\.jpg/, "detective activity should use a real six-finger classroom image");
assert.match(refreshScript, /car wash|洗车/, "detective activity should include the 50-meter car wash judgment");
assert.match(refreshScript, /hideApplauseStep/, "refresh script should remove the gift draw flow from the classroom rhythm");
assert.match(refreshScript, /五件重要的事/, "pass page should summarize five important things");
assert.match(refreshScript, /通关礼物/, "pass page should call the badge a pass gift");
assert.match(refreshCss, /cursor-sprinkle/, "refresh styles should render cursor sprinkles");
assert.match(refreshCss, /course-cover/, "refresh styles should render the fullscreen pre-class cover");
assert.match(refreshCss, /cover-animal/, "cover should render a fresh SVG cartoon animal mascot instead of Xiao Lili");
assert.match(refreshCss, /bunnyEars/, "cover animal should have CSS-driven cartoon motion");
assert.match(refreshCss, /cover-launch-burst/, "cover should style the fullscreen cartoon launch effect");
assert.match(refreshCss, /memory-workbench/, "refresh styles should render the AI generated memory game");
assert.match(refreshCss, /memory-card-grid/, "refresh styles should render the 12-card game grid");
assert.match(refreshCss, /fraud-image-frame/, "refresh styles should render the fraud awareness image carousel");
assert.match(refreshCss, /fraud-choice/, "refresh styles should render the fraud awareness answer buttons");
assert.match(refreshCss, /\.ai-fraud-refresh \.fraud-choice\.primary-action/, "AI fraud answer buttons should use neutral styling");
assert.match(refreshCss, /image-fullscreen-overlay/, "fullscreen image overlay should have styles");
assert.match(refreshCss, /detective-vote/, "refresh styles should render the new detective voting interaction");
assert.match(refreshCss, /repeat\(5, minmax\(0, 1fr\)\)/, "pass page should fit five summary cards");
assert.match(refreshCss, /ask-icon/, "pass page should use cartoon icon classes instead of text icons");
assert.match(refreshCss, /shield-icon/, "pass page should include a fraud-awareness cartoon icon");
for (const fileName of ["life-xiaoai-real.jpg", "life-vacuum-real.png", "life-car-real.jpg", "train-red-apple.jpg", "train-green-apple.jpg", "train-bitten-apple.jpg", "train-tomato-real.jpg", "six-fingers-photo.jpg", "ai1.png", "ai2.png", "ai3.png", "ai4.png", "lili-default.svg"]) {
  const imagePath = path.join(root, "images", fileName);
  assert.equal(fs.existsSync(imagePath), true, `refresh image should exist: images/${fileName}`);
  if (fileName.endsWith(".svg")) {
    assert.match(fs.readFileSync(imagePath, "utf8"), /<svg/, `refresh image should be an SVG: images/${fileName}`);
  } else {
    assert.ok(fs.statSync(imagePath).size > 1000, `refresh image should be a non-empty local image: images/${fileName}`);
  }
}

console.log("courseware structure checks passed");
